package com.example.demo.entities;
// Generated Dec 10, 2019, 8:57:54 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleAccountId generated by hbm2java
 */
@Embeddable
public class RoleAccountId implements java.io.Serializable {

	private int roleId;
	private int accountId;

	public RoleAccountId() {
	}

	public RoleAccountId(int roleId, int accountId) {
		this.roleId = roleId;
		this.accountId = accountId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleAccountId))
			return false;
		RoleAccountId castOther = (RoleAccountId) other;

		return (this.getRoleId() == castOther.getRoleId()) && (this.getAccountId() == castOther.getAccountId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getAccountId();
		return result;
	}

}
